# Generated by Django 5.0.3 on 2024-08-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_propertypost_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypost',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertypost',
            name='city',
            field=models.CharField(default='Lilongwe', max_length=50),
        ),
    ]
