# Generated by Django 5.0.3 on 2024-08-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propertypost_available_propertypost_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypost',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
